page_part_types:
  - text
  - photo
  - line

page_parts:
  default:
    - tag: left_column
      name: Linkerkolom
      content_type: text

    - tag: right_column
      name: Rechterkolom
      content_type: text

  homepage:
    - tag: linker_kolom
      name: linkerkolom
      content_type: text

  campers:
    - tag: oiwjfe
