page_part_types:
  - text
  - photo
  - photos
  - line
  - file
  - files

page_parts:
  default:
    - tag: header
      name: Headerfoto
      content_type: photo

    - tag: gallery
      name: Fotogalerij
      content_type: photos

    - tag: files
      name: Bijlagen
      content_type: files

    - tag: file
      name: Super PDF
      content_type: file

  homepage:
    - tag: left_column
      name: Linkerkolom
      content_type: text

    - tag: right_column
      name: Rechterkolom
      content_type: text

  contact:
    - tag: left_column
      name: Linkerkolom
      content_type: text

    - tag: right_column
      name: Rechterkolom
      content_type: text

plugins:
