page_part_types:
  - text
  - photo
  - line
  - file
  - files

page_parts:
  default:
    - tag: left_column
      name: Linkerkolom
      content_type: text

    - tag: right_column
      name: Rechterkolom
      content_type: text

    - tag: file
      name: Bestand
      content_type: file

    - tag: files
      name: Bestanden
      content_type: files

  homepage:
    - tag: left_column
      name: Linkerkolom
      content_type: text

    - tag: right_column
      name: Rechterkolom
      content_type: text

  contact:
    - tag: left_column
      name: Linkerkolom
      content_type: text

    - tag: right_column
      name: Rechterkolom
      content_type: text

plugins:
